blank_issues_enabled: false
contact_links:
  - name: Authok Community
    url: https://community.authok.com/c/sdks/5
    about: Discuss this SDK in the Authok Community forums
  - name: Library Documentation
    url: https://github.com/authok/authok-java/blob/master/README.md
    about: Read the library documentation
